import type { Metadata } from "next";
// NEED TO FIGURE THIS OUT!!!!!!!!
// import "app/Lowding/lowding-globals.css;";
import "./globals.css";

import { Providers } from "./Theme/Providers";
import Navbar from "./_components/Navbar";
import Footer from "./_components/Footer";

import { cn } from "../../../lib/utils";
import { Inconsolata } from "next/font/google";
import { Inter } from "next/font/google";
import MobileNavbar from "./_components/MobileNavbar";
import Ubernav from "@/app/_sharedComps/Ubernav";

const inter = Inter({ subsets: ["latin"] });
const inconsolata = Inconsolata({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn("tracking-wide", inconsolata.className)}>
        <Ubernav />
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
